/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MoviesIndexImport } from './routes/movies/index'
import { Route as ProfileUserIdImport } from './routes/profile.$userId'
import { Route as MoviesMovieIdImport } from './routes/movies/$movieId'

// Create/Update Routes

const MoviesIndexRoute = MoviesIndexImport.update({
  id: '/movies/',
  path: '/movies/',
  getParentRoute: () => rootRoute,
} as any)

const ProfileUserIdRoute = ProfileUserIdImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRoute,
} as any)

const MoviesMovieIdRoute = MoviesMovieIdImport.update({
  id: '/movies/$movieId',
  path: '/movies/$movieId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/movies/$movieId': {
      id: '/movies/$movieId'
      path: '/movies/$movieId'
      fullPath: '/movies/$movieId'
      preLoaderRoute: typeof MoviesMovieIdImport
      parentRoute: typeof rootRoute
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdImport
      parentRoute: typeof rootRoute
    }
    '/movies/': {
      id: '/movies/'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/movies': typeof MoviesIndexRoute
}

export interface FileRoutesByTo {
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/movies': typeof MoviesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/movies/': typeof MoviesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/movies/$movieId' | '/profile/$userId' | '/movies'
  fileRoutesByTo: FileRoutesByTo
  to: '/movies/$movieId' | '/profile/$userId' | '/movies'
  id: '__root__' | '/movies/$movieId' | '/profile/$userId' | '/movies/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  MoviesMovieIdRoute: typeof MoviesMovieIdRoute
  ProfileUserIdRoute: typeof ProfileUserIdRoute
  MoviesIndexRoute: typeof MoviesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  MoviesMovieIdRoute: MoviesMovieIdRoute,
  ProfileUserIdRoute: ProfileUserIdRoute,
  MoviesIndexRoute: MoviesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/movies/$movieId",
        "/profile/$userId",
        "/movies/"
      ]
    },
    "/movies/$movieId": {
      "filePath": "movies/$movieId.tsx"
    },
    "/profile/$userId": {
      "filePath": "profile.$userId.tsx"
    },
    "/movies/": {
      "filePath": "movies/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
